logging:
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      datadog:
        enabled: false
      jmx:
        enabled: true
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  security:
    enabled: false
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*xml

place_order_type: normal

server:
  port: 8090
  tomcat:
    threads:
      max: 500
  servlet:
    context-path: /api
spring:
  main:
    allow-circular-references: true
  application:
    name: flash-sale
  redis:
    address: redis://127.0.0.1:6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 30000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?serverTimezone=UTC&useUnicode=true
    username: thoughts-beta
    password: thoughts-beta
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      # 取消Sentinel控制台懒加载
      # 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
      # 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
      eager: true
